name: CreateNewSubmodule

# WORK IN PROGRESS

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      module_name:
        description: "Name of the submodule (eg. UrlUtils)"
        type: string
        required: true
      repo_name:
        description: "Name of the new repo (eg. ps_urlutils)"
        type: string
        required: true

jobs:
  init_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Create new submodule repository from template
        run: |
          gh repo create ${{ github.event.inputs.repo_name }} \
           --template=wookiefriseur/template_psmodule \
           --disable-wiki --disable-issues --public
        env:
          GITHUB_TOKEN: ${{ secrets.VM_CREATE_SUBMODULES }}

      - name: Edit new repository settings
        run: |
          REPO=wookiefriseur/${{ github.event.inputs.repo_name }}
          # make new repo available to gh cli and set as default for most actions
          git remote add new_module https://github.com/$REPO
          gh repo set-default $REPO

          gh label create 'version:MAJOR' --color D93F0B --description "Breaking changes (eg. 1.2.3 to 2.0.0)" --force
          gh label create 'version:MINOR' --color D93F0B --description "Regular changes (eg. 1.2.3 to 1.3.0)" --force
          gh label create 'version:PATCH' --color D93F0B --description "Tiny changes (eg. 1.2.3 to 1.2.4)" --force
          gh secret set VM_ACTIONS --app actions --body $NEW_REPO_SECRET -R $REPO

          echo '{
            "enforce_admins": false,
            "restrictions": null,
            "required_pull_request_reviews": {
                "dismiss_stale_reviews": false,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 0,
                "require_last_push_approval": false
            },
            "required_status_checks": {
                "strict": true,
                "contexts": ["run_tests"]
            }
          }' > payload.json

          gh api /repos/'{owner}'/'{repo}'/branches/main/protection \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           --method PUT --input payload.json
        env:
          NEW_REPO_SECRET: ${{ secrets.VM_ACTIONS }}
          GITHUB_TOKEN: ${{ secrets.VM_CREATE_SUBMODULES }}

  # ToDo:
  # - don't add/update submodule in here.
  # - use workflow_call from submodule to update_submodule_refs
  # - put add_submodule into update_submodule_refs.yml

  add_submodule:
    needs: init_repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          ref: main
          submodules: recursive
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add new submodule
        run: |
          git submodule add https://github.com/wookiefriseur/${{ github.event.inputs.repo_name }} psmodules/${{ github.event.inputs.module_name }}
          git config -f .gitmodules submodule.psmodules/${{ github.event.inputs.module_name }}.branch main

      - name: Commit changes
        run: |
          git commit --all --message "new module: ${{ github.event.inputs.module_name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
