name: Dummy

on:
  workflow_dispatch:

jobs:
  dummy_yummy:
    runs-on: windows-latest

    steps:
      - name: Handle large JSON escaping
        run: |
          Write-Output @"
          $($env:JSON)
          "@
        env:
          JSON: ${{ toJson(github.event) }}

      - name: Handling GITHUB_OUTPUT
        run: |
          Write-Output "✅ Path of env:GITHUB_OUTPUT: $($env:GITHUB_OUTPUT)"
          Write-Output "❌ MY_OUTPUT_VAR=output" >> $GITHUB_OUTPUT
          Write-Output "✅ Content env:GITHUB_OUTPUT:`n$(Get-Content $env:GITHUB_OUTPUT)"
          Write-Output "✅ MY_ENV_OUTPUT_VAR=env_output" >> $env:GITHUB_OUTPUT
          Write-Output "✅ Content env:GITHUB_OUTPUT:`n$(Get-Content $env:GITHUB_OUTPUT)"

      - name: Set Variables
        id: set_vars
        run: |
          $MY_REGULAR_VAR = "regular"
          $env:MY_ENV_VAR = "env"

      - name: Each step has separate session
        run: |
          Write-Output "❌ MY_REGULAR_VAR: $MY_REGULAR_VAR"
          Write-Output "❌ MY_ENV_VAR: $($env:MY_ENV_VAR)"
          Write-Output "❌ MY_OUTPUT_VAR: $($env:MY_OUTPUT_VAR)"
          Write-Output "❌ MY_ENV_OUTPUT_VAR: $($env:MY_ENV_OUTPUT_VAR)"

      - name: Retrieve vars from ENV and Step
        id: retrieval
        run: |
          Write-Output "❌ RETRIEVE_ENV_VAR directly: $RETRIEVE_ENV_VAR"
          Write-Output "✅ RETRIEVE_ENV_VAR from ENV: $($env:RETRIEVE_ENV_VAR)"
          Write-Output "❌ steps.set_vars.outputs.MY_OUTPUT_VAR: ${{ steps.set_vars.outputs.MY_OUTPUT_VAR }}"
          Write-Output "✅ steps.set_vars.outputs.MY_ENV_OUTPUT_VAR: ${{ steps.set_vars.outputs.MY_ENV_OUTPUT_VAR }}"
        env:
          RETRIEVE_ENV_VAR: "retrieval"
